import os
import time

from dotenv import load_dotenv
from google import genai
from google.genai import errors
from prometheus_client import Counter

load_dotenv()

client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY"),
    http_options=genai.types.HttpOptions(timeout=30000),
)

llm_input_tokens = Counter(
    "llm_input_tokens_total",
    "Total number of input tokens sent to the LLM",
)

llm_output_tokens = Counter(
    "llm_output_tokens_total",
    "Total number of output tokens generated by the LLM",
)


def generate_answer(question: str):
    for attempt in range(3):
        try:
            response = client.interactions.create(
                model="gemini-3.6-flash",
                input=question,
            )

            usage = getattr(response, "usage_metadata", None)

            if usage:
                input_tokens = getattr(
                    usage,
                    "prompt_token_count",
                    0,
                ) or 0

                output_tokens = getattr(
                    usage,
                    "candidates_token_count",
                    0,
                ) or 0

                llm_input_tokens.inc(input_tokens)
                llm_output_tokens.inc(output_tokens)

            return response.output_text

        except errors.RateLimitError:
            raise

        except Exception:
            if attempt == 2:
                raise

            time.sleep(2 ** attempt)

    raise RuntimeError("LLM request failed")